name: Splunk Appinspect Actions Demo
on: [push]
jobs:
  Package-and-Inspect-app:
    runs-on: ubuntu-latest
    steps:
      - name: Package app
        run: tar zcf app-package.tar.gz TA-app
      - name: Inspect app using Splunk AppInspect
        uses: splunk/appinspect-cli-action@v1.4.7-publish
        with:
          app_path: app-package.tar.gz
          included_tags: cloud