name: Splunk Appinspect Actions Demo
on: [push]
jobs:
  Inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Splunk AppInspect
        uses: splunk/appinspect-cli-action@v1.4.7-publish
        with:
          app_path: './TA-app'
          included_tags: cloud