name: Splunk Package, Vet and app
on: [push]
jobs:
  Package-and-Inspect-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download Splunk Packaging Toolkit (SLIM)
        run: |
          wget https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Install SLIM
        run: |
          pip install splunk-packaging-toolkit-1.0.1.tar.gz 
      - name: Generate app manifest
        run: | 
          slim generate-manifest TA-app -o TA-app/app.manifest
      - name: Package app
        run: |
          mkdir tmp && slim package TA-app --output-dir=tmp
      - name: Getting app name and saving to Github environment
        run: |
          echo "APPNAME=$(basename tmp/*tar.gz)" >> $GITHUB_ENV
      - name: Run Splunk AppInspect
        uses: splunk/appinspect-cli-action@v1.4.7-publish
        with:
          app_path: tmp/"${{ env.APPNAME }}"
          included_tags: cloud
      - name: Upload AppInspect Results
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.APPNAME }}"
          path: tmp/"${{ env.APPNAME }}"